[package]
name = "bottlerocket-license-scan"
version = "0.1.0"
description = "Collects and identifies licenses of Rust and Golang dependencies"
license = "Apache-2.0 OR MIT"
authors = ["iliana destroyer of worlds <iweller@amazon.com>"]
repository = "https://github.com/bottlerocket-os/bottlerocket-sdk"
edition = "2018"
keywords = ["license", "spdx", "ci"]
readme = "README.md"

[dependencies]
anyhow = "1"
askalono = "0.4"
cargo_metadata = "0.18"
ignore = "0.4"
lazy_static = "1"
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
spdx = "0.3"
structopt = { version = "0.3", default-features = false }
toml = "0.8"
twox-hash = "1"
walkdir = "2"

[dev-dependencies]
maplit = "1"
