name: Test bottlerocket-license-scan
on:
    pull_request:
        branches:
            - "*"
        paths:
            - "license-scan/**"
            - ".github/workflows/test-license-scan.yml"
jobs:
    build:
        runs-on:
            group: bottlerocket
            labels: bottlerocket_ubuntu-latest_8-core
        steps:
            - uses: actions/checkout@v3
            - run: rustup update stable
            - run: cargo install cargo-deny --locked
            - run: make build
              working-directory: ./license-scan
